version: '3'

services:

  mariadb: 
    image: mariadb:10.6.14
    container_name: mariadb
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
    volumes:
      - ./app/mariadb:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
    - MONGO_INITDB_ROOT_USERNAME= root
    - MONGO_INITDB_ROOT_PASSWORD= mypassword
    volumes:
    - ./app/mongodbdata:/data/db

  servidor:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DATABASE_USER: root
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: test

    restart: always
    depends_on:
      - mariadb
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./app:/server

